// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYCVCOX4NikN66zrMkqXaVGsIW85GU8yg',
    appId: '1:178974416087:web:09679fb3ae7862538ae492',
    messagingSenderId: '178974416087',
    projectId: 'dormnow-46dee',
    authDomain: 'dormnow-46dee.firebaseapp.com',
    storageBucket: 'dormnow-46dee.appspot.com',
    measurementId: 'G-2W4YPL3FQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPVJPcBXVccNRSqp1odiFZyneULRzOAfw',
    appId: '1:178974416087:android:0ab0f6780e10219e8ae492',
    messagingSenderId: '178974416087',
    projectId: 'dormnow-46dee',
    storageBucket: 'dormnow-46dee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBux94VnLpfMb4fpKq0UhctKl0OeCRM-8Y',
    appId: '1:178974416087:ios:fabf1da03ca21deb8ae492',
    messagingSenderId: '178974416087',
    projectId: 'dormnow-46dee',
    storageBucket: 'dormnow-46dee.appspot.com',
    iosBundleId: 'com.example.dormnow',
  );
}
